ARG FLAVOR=cpu
FROM ${FLAVOR}-road-core-base as road-core-rag-builder
ARG RHDH_DOCS_VERSION="1.4"
ARG NUM_WORKERS=1

USER 0
WORKDIR /workdir

COPY ./scripts/get_rhdh_plaintext_docs.sh ./
COPY ./scripts/asciidoctor-text ./asciidoctor-text
# Modify script inplace to account for new path
RUN sed -i 's/scripts\/asciidoctor-text/asciidoctor-text/' get_rhdh_plaintext_docs.sh
RUN dnf install rubygems -y &&\
    gem install asciidoctor
RUN ./get_rhdh_plaintext_docs.sh $RHDH_DOCS_VERSION

RUN for RHDH_VERSION in $(ls -1 rhdh-product-docs-plaintext); do \
        pdm run python rhdh_generate_embeddings.py -f rhdh-product-docs-plaintext/${RHDH_VERSION} -md embeddings_model \
            -mn ${EMBEDDING_MODEL} -o vector_db/rhdh_product_docs/${RHDH_VERSION} -w ${NUM_WORKERS} \
            -i rhdh-product-docs-$(echo $RHDH_VERSION | sed 's/\./_/g') -t asciidoctor-text/rhdh_topic_map.yaml -v ${RHDH_VERSION}; \
    done

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
COPY --from=road-core-rag-builder /workdir/vector_db/rhdh_product_docs /rag/vector_db/rhdh_product_docs
COPY --from=road-core-rag-builder /workdir/embeddings_model /rag/embeddings_model

# this directory is checked by ecosystem-cert-preflight-checks task in Konflux
RUN mkdir /licenses
COPY LICENSE /licenses/

# Labels for enterprise contract
LABEL com.redhat.component=openshift-lightspeed-rag-content
LABEL description="Red Hat Developer Hub Lightspeed RAG content"
LABEL distribution-scope=private
LABEL io.k8s.description="Red Hat Developer Hub Lightspeed RAG content"
LABEL io.k8s.display-name="Openshift Lightspeed RAG content"
LABEL io.openshift.tags="openshift,lightspeed,ai,assistant,rag"
LABEL name=openshift-lightspeed-rag-content
LABEL release=0.0.1
LABEL url="https://github.com/openshift/lightspeed-rag-content"
LABEL vendor="Red Hat, Inc."
LABEL version=0.0.1
LABEL summary="Red Hat Developer Hub Lightspeed RAG content"

USER 65532:65532
